policy: 'MlpPolicy'
learning_rate: 0.0007
n_steps: 5
gamma: 0.99
gae_lambda: 1.0
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
use_rms_prop: True
normalize_advantage: False
policy_kwargs: 'dict(
  net_arch=[dict(pi=[64, 64], vf=[64, 64])],
  activation_fn=nn.Tanh,
  ortho_init=True
)'

