policy: 'MlpPolicy'
learning_rate: 0.0001
buffer_size: 1000000
learning_starts: 50000
batch_size: 32
gamma: 0.99
train_freq: 4
gradient_steps: 1
target_update_interval: 10000
exploration_fraction: 0.1
exploration_final_eps: 0.05
policy_kwargs: 'dict(
  net_arch=[64, 64]
)'